include:
  - ./MSVCs-Base/compose.yml
services:
  users-details-db:
    container_name: "users-details-db"
    image: "mysql:latest"
    ports:
      - "3308:3306"
    networks:
      - uwhub-network
    volumes:
      - user-detail-data:/etc/mysql/conf.d
    environment:
      - "MYSQL_DATABASE=users_details_db"
      - "MYSQL_ROOT_PASSWORD=root123"

  msvc-user-details:
    build:
      context: ./msvc-user-details
      dockerfile: Dockerfile
    container_name: msvc-user-details
    ports:
      - "8081:8081"
    depends_on:
      - users-details-db
    env_file:
      - ./MSVCs-Base/.env.dev
      - ./msvc-user-details/.env
    networks:
      - uwhub-network
    restart: always

volumes:
  user-detail-data:
