FROM openjdk:17-alpine AS builder

WORKDIR /app/

COPY ./.mvn/ /app/.mvn/
COPY ./mvnw /app
COPY ./pom.xml /app

RUN /app/mvnw dependency:go-offline

COPY ./src/ /app/src/

RUN /app/mvnw clean package -DskipTests

FROM openjdk:17-alpine

WORKDIR /app/

COPY --from=builder /app/target/msvc-user-details-0.0.1-SNAPSHOT.jar /app/msvc-user-details-0.0.1-SNAPSHOT.jar

CMD [ "java", "-jar", "msvc-user-details-0.0.1-SNAPSHOT.jar"]